const CONSTANTS = Object.freeze({
  navigation: Object.freeze({
    brand: "CareBridge 24x7",
    brandAriaLabel: "CareBridge 24x7 home",
    primaryAriaLabel: "Primary",
    routes: Object.freeze({
      login: "Home",
      dashboard: "Dashboard",
      doctors: "Doctors",
      appointments: "Appointments",
      medicines: "Medicines",
      healthRecords: "Health Records",
      orders: "Orders",
      profile: "Profile",
    }),
    logout: "Logout",
  }),
  session: Object.freeze({
    restoring: "Restoring session...",
  }),
  auth: Object.freeze({
    heroEyebrow: "Unified care, wherever you are",
    heroTitle: "CareBridge keeps your care journey in sync.",
    heroDescription:
      "Sign in to book appointments, browse doctors, manage medicines, review health records, and keep your profile updated across web and mobile.",
    welcomeBack: "Welcome back to CareBridge",
    demoBanner:
      "Demo accounts: Patient Demo uses patient1 / patient123. Doctor or Admin Demo uses admin / admin123.",
    tabs: Object.freeze({
      login: "Login",
      register: "Register",
    }),
    roles: Object.freeze({
      patient: "Patient",
      doctor: "Doctor",
    }),
    labels: Object.freeze({
      username: "Username",
      password: "Password",
      fullName: "Full Name",
      email: "Email",
      phone: "Phone",
      address: "Address",
      service: "Select service",
    }),
    placeholders: Object.freeze({
      username: "Username",
      password: "Password",
      fullName: "Full name",
      email: "Email",
      phone: "Phone",
      address: "Street, city, state",
    }),
    serviceOptions: Object.freeze({
      patient: Object.freeze([
        "General Consultation",
        "Follow-up",
        "Second Opinion",
        "Wellness",
      ]),
      doctor: Object.freeze([
        "Doctor Login",
        "Teleconsult Panel",
        "Hospital Dashboard",
        "ePrescription",
      ]),
    }),
    highlights: Object.freeze([
      "General Physician",
      "Dermatology",
      "Cardiology",
      "Lab Tests",
      "Medicine Delivery",
      "Health Records",
    ]),
    buttons: Object.freeze({
      loading: "Please wait...",
      login: "Login",
      createAccount: "Create Account",
      signingIn: "Signing in...",
      continueAsPatient: "Continue as Patient",
      continueAsDoctor: "Continue as Doctor",
      useAdminDemo: "Use admin demo",
      usePatientDemo: "Use patient demo",
      useDoctorAdminDemo: "Use Doctor/Admin Demo",
    }),
    hints: Object.freeze({
      registerAtCheckout:
        "New user? You can create an account while confirming your appointment.",
    }),
    demoAccounts: Object.freeze({
      admin: Object.freeze({
        username: "admin",
        password: "admin123",
      }),
      patient: Object.freeze({
        username: "patient1",
        password: "patient123",
      }),
    }),
  }),
  doctors: Object.freeze({
    eyebrow: "Specialist Directory",
    title: "Available Doctors",
    description:
      "Browse specialists, hospital details, consultation fee, and availability in a single shared directory.",
    loading: "Loading specialists...",
    fields: Object.freeze({
      specialty: "Specialty",
      experience: "Experience",
      rating: "Rating",
      fee: "Fee",
      availability: "Availability",
      yearsSuffix: "yrs",
      ratingSuffix: "/ 5",
    }),
    bookButton: "Book Appointment",
  }),
  appointments: Object.freeze({
    eyebrow: "Appointment Desk",
    title: "Book an Appointment",
    description:
      "Continue as guest while browsing. Authentication is only required when confirming the booking.",
    labels: Object.freeze({
      selectDoctor: "Select Doctor",
      appointmentType: "Appointment Type",
      selectDate: "Select Date",
      selectTime: "Select Time",
      reason: "Reason for Visit",
      myAppointments: "My Appointments",
      reasonPrefix: "Reason",
    }),
    placeholders: Object.freeze({
      doctorSelect: "-- Select a Doctor --",
      reason: "Describe symptoms or consultation purpose",
      authName: "Full name",
      authEmail: "Email",
      authPhone: "Phone",
      authUsername: "Username",
      authPassword: "Password",
    }),
    types: Object.freeze(["Consultation", "Follow-up", "Routine Check"]),
    errors: Object.freeze({
      incompleteDetails:
        "Please complete all appointment details before confirming.",
      authenticationFailed: "Authentication failed",
    }),
    buttons: Object.freeze({
      processing: "Processing...",
      proceedToPayment: "Confirm Appointment",
      loginToContinue: "Login to Confirm",
      createAccount: "Create Account",
      cancel: "Cancel",
      confirmAndPay: "Confirm Appointment",
    }),
    modal: Object.freeze({
      description:
        "Complete authentication to confirm the appointment and finalize your booking.",
      emptyAppointments: "No appointments yet.",
    }),
  }),
  checkout: Object.freeze({
    title: "Medicine Checkout",
    description: "Review your medicine cart and proceed with order placement.",
    backToMedicines: "Back to Medicines",
    cartItems: "Cart Items",
    clearCart: "Clear Cart",
    emptyCart: "Your cart is empty. Add medicines to continue.",
    remove: "Remove",
    orderSummary: "Order Summary",
    subtotal: "Subtotal",
    delivery: "Delivery",
    freeDelivery: "FREE",
    total: "Total",
    placeOrderLoading: "Placing Order...",
    loginToPlaceOrder: "Login to Place Order",
    placeOrder: "Place Medicine Order",
  }),
  healthRecords: Object.freeze({
    eyebrow: "Secure Archive",
    title: "Health Records",
    description: "Past prescriptions and doctor notes from previous visits.",
    unauthenticatedMessage: "Please login to access your health records.",
    loading: "Loading health records...",
    empty: "No prescriptions found yet.",
    downloadAll: "Download All Records",
    downloadOne: "Download Record",
    prescribedMedicines: "Prescribed medicines",
    doctorNotes: "Doctor notes",
    consultantLabel: "Consultant",
    exportFailureTitle: "Export failed",
    exportSingleFailurePrefix:
      "Unable to export this prescription PDF right now.",
    exportAllFailurePrefix: "Unable to export prescription PDFs right now.",
    shareMessage: "CareBridge prescription PDF",
    shareTitle: "Prescription PDF",
    document: Object.freeze({
      pageTitle: "CareBridge Health Records",
      clinicName: "CareBridge Multi-Specialty Clinic",
      clinicSub:
        "12 Wellness Avenue, San Francisco, CA • +1 (555) 010-9000 • carebridge.health",
      prescriptionIdLabel: "Prescription ID",
      dateLabel: "Date",
      title: "Official Prescription",
      consultantLabel: "Consultant",
      diagnosisLabel: "Diagnosis",
      prescribedMedicinesLabel: "Prescribed Medicines",
      clinicalNotesLabel: "Clinical Notes",
      signaturePrefix: "Digitally signed by",
      stampText: "CareBridge Verified Prescription",
      singleFilePrefix: "carebridge-prescription",
      allFilePrefix: "carebridge-all-prescriptions",
      browserFilePrefix: "carebridge-health-records",
      browserRecordPrefix: "carebridge-record",
    }),
  }),
  orders: Object.freeze({
    eyebrow: "Fulfillment Tracker",
    title: "Medicine Orders",
    description: "Track your medicine orders and delivery status.",
    loading: "Loading orders...",
    empty: "No medicine orders yet.",
    unauthenticatedMessage: "Please login to track your medicine orders.",
    orderPrefix: "Order #",
    placedLabel: "Placed",
    etaLabel: "ETA",
    itemsLabel: "Items",
    summaryLabel: "Summary",
    totalLabel: "Total",
  }),
  profile: Object.freeze({
    eyebrow: "Patient Hub",
    title: "Patient Profile",
    description:
      "Keep your contact details, address, and health condition current across web and mobile.",
    unauthenticatedMessage: "Login to manage your profile.",
    labels: Object.freeze({
      name: "Full Name",
      email: "Email",
      phone: "Phone",
      address: "Address",
      condition: "Condition",
      signedInAs: "Signed in as",
      syncStatus: "Sync status",
    }),
    placeholders: Object.freeze({
      name: "Full name",
      email: "Email",
      phone: "Phone",
      address: "Street, city, state",
      condition: "Condition",
    }),
    buttons: Object.freeze({
      saving: "Saving...",
      save: "Save Profile",
    }),
    messages: Object.freeze({
      updatedTitle: "Profile updated",
      updatedBody: "Your profile has been saved.",
      updatedInline: "Profile updated successfully.",
      sharedData: "Shared profile data is used by both apps.",
      ready: "Ready",
      loading: "Loading",
      saving: "Saving",
    }),
  }),
  feedback: Object.freeze({
    errors: Object.freeze({
      auth: Object.freeze({
        initialize: "Failed to initialize auth",
        login: "Login failed",
        register: "Registration failed",
      }),
      appointments: Object.freeze({
        fetch: "Failed to fetch appointments",
        create: "Failed to create appointment",
      }),
      doctors: Object.freeze({
        fetch: "Failed to fetch doctors",
      }),
      medicines: Object.freeze({
        fetch: "Failed to load medicines",
      }),
      profile: Object.freeze({
        fetch: "Failed to fetch profile",
        save: "Failed to save profile",
      }),
      healthRecords: Object.freeze({
        fetch: "Failed to fetch health records",
      }),
      orders: Object.freeze({
        fetch: "Failed to fetch orders",
        place: "Failed to place order",
      }),
    }),
  }),
});

module.exports = {
  sharedUiCopy: CONSTANTS,
};
